# Конфигурационный файл
apiPrefix: "/api"

server:
    port: 8085

spring:

  # Подключение к H2 бд через jdbc
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://localhost:5432/attendance-log
    driverClassName: org.postgresql.Driver
    username: root
    password: root

  # Включение консоли
  h2:
    console:
      #enabled: false
      enabled: true
      settings:
        web-allow-others: true

  jpa:

    #Автогенерация схемы hibernate
    #generate-ddl: false
    generate-ddl: true


    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: none
#      ddl-auto: create
      ddl-auto: update

    # Показываем запросы
    show-sql: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method